### ISSUE TITLE
Builded still a long loading Building module bundle for production... And nerver stop

### ISSUE THREAD

**Issue by MygengBin** [Tofandel/prerender-spa-plugin-next#25]
I am use `npx @vue/cli create . ` build vue project.
Then i am use` npm i prerender-spa-plugin-next`

This is my text of the vue.config.js
```javascript
const { defineConfig } = require('@vue/cli-service');
const PrerenderSPAPlugin = require('prerender-spa-plugin-next');

module.exports = defineConfig({
    transpileDependencies: true,
    publicPath:'/',
    configureWebpack:config => {
        const prerenderCfg = new PrerenderSPAPlugin({
            routes: ["/", "/about"],
            renderOptions: {
                renderAfterDocumentEvent: "prerender",
            },

            rendererOptions: {
                // headless: false,
                renderAfterDocumentEvent: "render-event",
                // inject: {},
                // timeout: 10000,
            },
        });
        config.plugins.push(prerenderCfg);
    }
})
```

This is the result. never stop.

![image](https://user-images.githubusercontent.com/53421034/197445458-3e3bbb3d-78e8-4070-902d-b26bb01532a6.png)

**Comment by Tofandel** [comment]
You use `renderAfterDocumentEvent: "render-event",` but never mention actually implementing this event in your vue app, if this event is not received, the build will never finish

You need to fire `document.dispatchEvent(new Event('render-event'))` in your app's mounted hook


You should also delete the `renderOptions` option which doesn't exist

**Comment by MygengBin** [comment]
> You use `renderAfterDocumentEvent: "render-event",` but never mention actually implementing this event in your vue app, if this event is not received, the build will never finish
> 
> You need to fire `document.dispatchEvent(new Event('render-event'))` in your app's mounted hook
> 
> You should also delete the `renderOptions` option which doesn't exist

Thank you help me. Actually  i worte `document.dispatchEvent(new Event('render-event'))` in App.vue. but it still never finish.

Now it ok after deleted when i seen your told should delete the `renderOptions`.

Thank you very much
