### ISSUE TITLE
Outdated puppeteer

### ISSUE THREAD

**Issue by nick-msm** [Tofandel/prerender-spa-plugin-next#9]
Firstly, thanks for your efforts making `prerender-spa-plugin` compatible with Webpack5.

I've noticed that this repo relies on `@prerenderer/renderer-puppeteer` which hasn't been updated for 4 years, meaning that the version of Chromium used (78.0.3882.0) is also out of date by a substantial margin as puppeteer pairs its version with a single compatible Chromium version, [see version compatibility here](https://github.com/puppeteer/puppeteer/blob/main/versions.js#L20-L44). 

I've attempted to pin the puppeteer version like so:

 ```
 "resolutions": {
    "prerender-spa-plugin-next/**/puppeteer": "^13.0.0"
  }
  ```
  
But unfortunately I haven't been able to get this to work.

Do you have any advice on how to use a more recent version of puppeteer so that I can leverage more recent chromium features than v78 offers?

**Comment by KutnerUri** [comment]
heyo, I had the some problem (getting error "cannot read .close() of undefined") so I went ahead an upgraded the puppeteer prerenderer :)

https://bit.cloud/teambit/react/modules/prerenderer-puppeteer

you can go ahead and install it:
```
@teambit/react.modules.prerenderer-puppeteer
```

v0.0.1 comes with Puppeteer `14.1.0`,
v0.0.2+ comes with v`13.7.0` (because it is compatible with Node 12)

**Comment by Tofandel** [comment]
Hi, sorry it took so long to reply, I didn't have notifications turned on for this project

The problem is that puppeteer is a deep dependency
So I would need to fork the renderer as well to update it, which I might do

**Comment by Tofandel** [comment]
I have finally released a full suite upgrade, the plugin is now available under [`@prerenderer/webpack-plugin`](https://github.com/JoshTheDerf/prerenderer) 

I'm deprecating this package and archiving the repo
